/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twt_service_JniUtils */

#ifndef _Included_com_twt_service_JniUtils
#define _Included_com_twt_service_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twt_service_JniUtils
 * Method:    getAppKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twt_service_JniUtils_getAppKey
  (JNIEnv *, jobject);

/*
 * Class:     com_twt_service_JniUtils
 * Method:    getAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twt_service_JniUtils_getAppSecret
  (JNIEnv *, jobject);

/*
 * Class:     com_twt_service_JniUtils
 * Method:    getFirApiToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twt_service_JniUtils_getFirApiToken
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
