/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rex_wepeiyang_JniUtils */

#ifndef _Included_com_rex_wepeiyang_JniUtils
#define _Included_com_rex_wepeiyang_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rex_wepeiyang_JniUtils
 * Method:    getAppKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rex_wepeiyang_JniUtils_getAppKey
  (JNIEnv *, jobject);

/*
 * Class:     com_rex_wepeiyang_JniUtils
 * Method:    getAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rex_wepeiyang_JniUtils_getAppSecret
  (JNIEnv *, jobject);

/*
 * Class:     com_rex_wepeiyang_JniUtils
 * Method:    getFirApiToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rex_wepeiyang_JniUtils_getFirApiToken
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
