package com.inst.greendao3_demo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bdpqchen.yellowpagesmodule.yellowpages.model.Collected;
import com.bdpqchen.yellowpagesmodule.yellowpages.model.History;
import com.bdpqchen.yellowpagesmodule.yellowpages.model.Phone;

import com.inst.greendao3_demo.dao.CollectedDao;
import com.inst.greendao3_demo.dao.HistoryDao;
import com.inst.greendao3_demo.dao.PhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectedDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig phoneDaoConfig;

    private final CollectedDao collectedDao;
    private final HistoryDao historyDao;
    private final PhoneDao phoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectedDaoConfig = daoConfigMap.get(CollectedDao.class).clone();
        collectedDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        phoneDaoConfig = daoConfigMap.get(PhoneDao.class).clone();
        phoneDaoConfig.initIdentityScope(type);

        collectedDao = new CollectedDao(collectedDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        phoneDao = new PhoneDao(phoneDaoConfig, this);

        registerDao(Collected.class, collectedDao);
        registerDao(History.class, historyDao);
        registerDao(Phone.class, phoneDao);
    }
    
    public void clear() {
        collectedDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
        phoneDaoConfig.clearIdentityScope();
    }

    public CollectedDao getCollectedDao() {
        return collectedDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public PhoneDao getPhoneDao() {
        return phoneDao;
    }

}
